# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function: Eigen-decompose a matrix
#' @keywords internal
#' @param matrix A matrix
#' @return A list of objects
#' \item{value}{A vector of eigenvalues}
#' \item{vector}{A matrix of eigenvectors}
#' @author Wen-Ting Wang
eigenDecompose <- function(matrix) {
    .Call(`_autoFRK_eigenDecompose`, matrix)
}

#' Internal function: A wrapper function of 'MatrixBase::sqrt()'
#' @keywords internal
#' @param matrix A matrix
#' @return A matrix
#' @author Wen-Ting Wang
getSquareRootMatrix <- function(matrix) {
    .Call(`_autoFRK_getSquareRootMatrix`, matrix)
}

#' Internal function: Inverse square root matrix of  A^t * B
#' @keywords internal
#' @param left_matrix A matrix
#' @param right_matrix A matrix
#' @return A matrix
#' @author Wen-Ting Wang
getInverseSquareRootMatrix <- function(left_matrix, right_matrix) {
    .Call(`_autoFRK_getInverseSquareRootMatrix`, left_matrix, right_matrix)
}

#' Internal function: Compute MRTS method
#' @keywords internal
#' @param s A location matrix
#' @param xobs_diag A matrix of observations
#' @param k A rank
#' @return A list of objects
#' \item{X}{A matrix}
#' \item{UZ}{A matrix}
#' \item{BBBH}{A matrix}
#' \item{nconst}{A vector of column means}
#' @author Wen-Ting Wang
computeMrtsRcpp <- function(s, xobs_diag, k) {
    .Call(`_autoFRK_computeMrtsRcpp`, s, xobs_diag, k)
}

#' Internal function: Predict on new locatoins by MRTS method
#' @keywords internal
#' @param s A location matrix
#' @param xobs_diag A matrix of observations
#' @param s_new A new location matrix
#' @param k A rank
#' @return A list of objects
#' \item{X}{A matrix}
#' \item{UZ}{A matrix}
#' \item{BBBH}{A matrix}
#' \item{nconst}{A vector of column means}
#' \item{X1}{A matrix}
#' @author Wen-Ting Wang
predictMrtsRcpp <- function(s, xobs_diag, s_new, k) {
    .Call(`_autoFRK_predictMrtsRcpp`, s, xobs_diag, s_new, k)
}

#' Internal function: Predict on new locatoins by MRTS method
#' @keywords internal
#' @param s A location matrix
#' @param xobs_diag A matrix of observations
#' @param s_new A new location matrix
#' @param BBBH A matrix for internal computing use
#' @param UZ A matrix for internal computing use
#' @param nconst A A vector of column means
#' @param k A rank
#' @return A list of objects
#' \item{X}{A matrix}
#' \item{UZ}{A matrix}
#' \item{BBBH}{A matrix}
#' \item{nconst}{A vector of column means}
#' \item{X1}{A matrix}
#' @author Wen-Ting Wang
predictMrtsRcppWithBasis <- function(s, xobs_diag, s_new, BBBH, UZ, nconst, k) {
    .Call(`_autoFRK_predictMrtsRcppWithBasis`, s, xobs_diag, s_new, BBBH, UZ, nconst, k)
}

