# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mrtsRcpp <- function(Xu, xobs_diag, k) {
    .Call(`_autoFRK_mrtsRcpp`, Xu, xobs_diag, k)
}

predictMrtsRcpp <- function(Xu, xobs_diag, xnew, k) {
    .Call(`_autoFRK_predictMrtsRcpp`, Xu, xobs_diag, xnew, k)
}

predictMrtsRcppWithBasis <- function(Xu, xobs_diag, xnew, BBBH, UZ, nconst, k) {
    .Call(`_autoFRK_predictMrtsRcppWithBasis`, Xu, xobs_diag, xnew, BBBH, UZ, nconst, k)
}

