# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mrtsRcpp <- function(s, xobs_diag, k) {
    .Call(`_autoFRK_mrtsRcpp`, s, xobs_diag, k)
}

predictMrtsRcpp <- function(s, xobs_diag, s_new, k) {
    .Call(`_autoFRK_predictMrtsRcpp`, s, xobs_diag, s_new, k)
}

predictMrtsRcppWithBasis <- function(s, xobs_diag, s_new, BBBH, UZ, nconst, k) {
    .Call(`_autoFRK_predictMrtsRcppWithBasis`, s, xobs_diag, s_new, BBBH, UZ, nconst, k)
}

inverseR <- function(s, tau, nu, rho, sigma2) {
    .Call(`_autoFRK_inverseR`, s, tau, nu, rho, sigma2)
}

